// Generated by node scripts/boolean-callbacks.mjs. Do not edit.
import type { GitBooleanProfile } from './git-boolean.js';
import type { GitIntegerParser } from './git-integer.js';
export const BOOLEAN_GRAMMAR = {
  true: ['true', 'yes', 'on'],
  false: ['', 'false', 'no', 'off'],
  integer: {
    kind: 'integer',
    signed: true,
    bits: 32,
  },
} as const satisfies {
  true: readonly string[];
  false: readonly string[];
  integer: GitIntegerParser;
};
export const BOOLEAN_CALLBACKS = {
  'git-bool': {
    allowTrue: true,
    names: {},
    source:
      'submodule-config.c:parse_update_recurse; submodule.c:option_parse_recurse_submodules_worktree_updater',
  },
  'fetch-recurse': {
    allowTrue: true,
    names: {
      'on-demand': 'on-demand',
    },
    source: 'submodule-config.c:parse_fetch_recurse/option_fetch_parse_recurse_submodules',
  },
  'push-recurse': {
    allowTrue: false,
    names: {
      'on-demand': 'on-demand',
      check: 'check',
      only: 'only',
    },
    source: 'submodule-config.c:parse_push_recurse; builtin/push.c:option_parse_recurse_submodules',
    transitions: {
      'only-is-on-demand': {
        from: 'only',
        to: 'on-demand',
      },
    },
  },
  'push-signed': {
    allowTrue: true,
    names: {
      'if-asked': 'if-asked',
    },
    source: 'send-pack.c:option_parse_push_signed',
    caseInsensitive: true,
  },
  'pull-rebase': {
    allowTrue: true,
    names: {
      merges: 'merges',
      m: 'merges',
      interactive: 'interactive',
      i: 'interactive',
    },
    source: 'rebase.c:rebase_parse_value; builtin/pull.c:parse_opt_rebase',
  },
} as const satisfies Record<string, GitBooleanProfile>;
