import type { Constraint } from './model.js';
import { NUMERIC_CALLBACK_PARSERS } from './numeric-callbacks.generated.js';

const git = (file: string) => `https://github.com/git/git/blob/v2.48.0/${file}`;
const lfs = (command: string) =>
  `https://github.com/git-lfs/git-lfs/blob/v3.6.1/docs/man/git-lfs-${command}.adoc`;
const contract = 'docs/design/option-constraints.md';
const active = <const K extends string>(key: K) => ({ key, test: 'active' }) as const;
const present = <const K extends string>(key: K) => ({ key, test: 'present' }) as const;
const equal = <const K extends string, const V extends string | boolean>(key: K, value: V) =>
  ({ key, test: 'equals', value }) as const;

/** Version-pinned evidence records a reviewed baseline, not a claim about every Git version. */
export const COMMAND_CONSTRAINTS = {
  lfsMigrateInfo: [
    {
      id: 'lfsMigrateInfo.everything-includeRef',
      kind: 'forbid',
      when: [
        {
          key: 'everything',
          test: 'active',
        },
        {
          key: 'includeRef',
          test: 'nonempty',
        },
      ],
      origin: 'git',
      reason: 'Everything cannot be combined with explicit reference selection.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate.go',
    },
    {
      id: 'lfsMigrateInfo.everything-excludeRef',
      kind: 'forbid',
      when: [
        {
          key: 'everything',
          test: 'active',
        },
        {
          key: 'excludeRef',
          test: 'nonempty',
        },
      ],
      origin: 'git',
      reason: 'Everything cannot be combined with explicit reference selection.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate.go',
    },
    {
      id: 'lfsMigrateInfo.everything-refs',
      kind: 'forbid',
      when: [
        {
          key: 'everything',
          test: 'active',
        },
        {
          key: 'refs',
          test: 'nonempty',
        },
      ],
      origin: 'git',
      reason: 'Everything cannot be combined with explicit reference selection.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate.go',
    },
    {
      id: 'lfsMigrateInfo.fixup-patterns',
      kind: 'conflicts',
      when: {
        key: 'fixup',
        test: 'active',
      },
      others: [
        {
          key: 'include',
          test: 'present',
        },
        {
          key: 'exclude',
          test: 'present',
        },
      ],
      origin: 'git',
      reason: 'Fixup infers patterns from attributes and rejects explicit include/exclude.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate_info.go',
    },
    {
      id: 'lfsMigrateInfo.fixup-pointers',
      kind: 'conflicts',
      when: {
        key: 'fixup',
        test: 'active',
      },
      others: [
        {
          key: 'pointers',
          test: 'equals',
          value: 'follow',
        },
        {
          key: 'pointers',
          test: 'equals',
          value: 'no-follow',
        },
      ],
      origin: 'git',
      reason: 'Fixup accepts only the ignore pointer mode.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate_info.go',
    },
  ],
  lfsMigrateImport: [
    {
      id: 'lfsMigrateImport.above-include',
      kind: 'forbid',
      when: [
        { key: 'noRewrite', test: 'inactive' },
        { key: 'above', test: 'bytesPositive' },
        { key: 'include', test: 'present' },
      ],
      origin: 'git',
      reason:
        'Positive size thresholds cannot be combined with explicit filters or fixup when rewriting history.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate_import.go',
    },
    {
      id: 'lfsMigrateImport.above-exclude',
      kind: 'forbid',
      when: [
        { key: 'noRewrite', test: 'inactive' },
        { key: 'above', test: 'bytesPositive' },
        { key: 'exclude', test: 'present' },
      ],
      origin: 'git',
      reason:
        'Positive size thresholds cannot be combined with explicit filters or fixup when rewriting history.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate_import.go',
    },
    {
      id: 'lfsMigrateImport.above-fixup',
      kind: 'forbid',
      when: [
        { key: 'noRewrite', test: 'inactive' },
        { key: 'above', test: 'bytesPositive' },
        { key: 'fixup', test: 'active' },
      ],
      origin: 'git',
      reason:
        'Positive size thresholds cannot be combined with explicit filters or fixup when rewriting history.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate_import.go',
    },
    {
      id: 'lfsMigrateImport.everything-includeRef',
      kind: 'forbid',
      when: [
        {
          key: 'noRewrite',
          test: 'inactive',
        },
        {
          key: 'everything',
          test: 'active',
        },
        {
          key: 'includeRef',
          test: 'nonempty',
        },
      ],
      origin: 'git',
      reason: 'Everything cannot be combined with explicit reference selection.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate.go',
    },
    {
      id: 'lfsMigrateImport.everything-excludeRef',
      kind: 'forbid',
      when: [
        {
          key: 'noRewrite',
          test: 'inactive',
        },
        {
          key: 'everything',
          test: 'active',
        },
        {
          key: 'excludeRef',
          test: 'nonempty',
        },
      ],
      origin: 'git',
      reason: 'Everything cannot be combined with explicit reference selection.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate.go',
    },
    {
      id: 'lfsMigrateImport.everything-refs',
      kind: 'forbid',
      when: [
        {
          key: 'noRewrite',
          test: 'inactive',
        },
        {
          key: 'everything',
          test: 'active',
        },
        {
          key: 'refs',
          test: 'nonempty',
        },
      ],
      origin: 'git',
      reason: 'Everything cannot be combined with explicit reference selection.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate.go',
    },
    {
      id: 'lfsMigrateImport.unknown-options',
      kind: 'unsupported',
      keys: ['object', 'top', 'unit', 'pointers'],
      origin: 'git',
      reason: 'These options do not exist for migrate import.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate.go',
    },
    {
      id: 'lfsMigrateImport.no-rewrite-fixup',
      kind: 'exclusive',
      keys: ['noRewrite', 'fixup'],
      origin: 'git',
      reason: 'No-rewrite and fixup cannot be combined.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate_import.go',
    },
    {
      id: 'lfsMigrateImport.files',
      kind: 'requires',
      when: {
        key: 'noRewrite',
        test: 'active',
      },
      required: [
        {
          key: 'files',
          test: 'nonempty',
        },
      ],
      origin: 'git',
      reason: 'No-rewrite requires one or more positional files.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate_import.go',
    },
    {
      id: 'lfsMigrateImport.file-mode',
      kind: 'requires',
      when: {
        key: 'files',
        test: 'nonempty',
      },
      required: [
        {
          key: 'noRewrite',
          test: 'active',
        },
      ],
      origin: 'type-git',
      reason: 'The files property denotes no-rewrite paths; use refs to select history.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate_import.go',
    },
    {
      id: 'lfsMigrateImport.refs-mode',
      kind: 'conflicts',
      when: {
        key: 'noRewrite',
        test: 'active',
      },
      others: [
        {
          key: 'refs',
          test: 'nonempty',
        },
      ],
      origin: 'type-git',
      reason: 'No-rewrite operands are files; use the files property in this mode.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate_import.go',
    },
    {
      id: 'lfsMigrateImport.fixup-patterns',
      kind: 'conflicts',
      when: {
        key: 'fixup',
        test: 'active',
      },
      others: [
        {
          key: 'include',
          test: 'present',
        },
        {
          key: 'exclude',
          test: 'present',
        },
      ],
      origin: 'git',
      reason: 'Fixup infers patterns from attributes and rejects explicit include/exclude.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate_import.go',
    },
  ],
  lfsMigrateExport: [
    {
      id: 'lfsMigrateExport.everything-includeRef',
      kind: 'forbid',
      when: [
        {
          key: 'everything',
          test: 'active',
        },
        {
          key: 'includeRef',
          test: 'nonempty',
        },
      ],
      origin: 'git',
      reason: 'Everything cannot be combined with explicit reference selection.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate.go',
    },
    {
      id: 'lfsMigrateExport.everything-excludeRef',
      kind: 'forbid',
      when: [
        {
          key: 'everything',
          test: 'active',
        },
        {
          key: 'excludeRef',
          test: 'nonempty',
        },
      ],
      origin: 'git',
      reason: 'Everything cannot be combined with explicit reference selection.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate.go',
    },
    {
      id: 'lfsMigrateExport.everything-refs',
      kind: 'forbid',
      when: [
        {
          key: 'everything',
          test: 'active',
        },
        {
          key: 'refs',
          test: 'nonempty',
        },
      ],
      origin: 'git',
      reason: 'Everything cannot be combined with explicit reference selection.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate.go',
    },
    {
      id: 'lfsMigrateExport.include',
      kind: 'required',
      required: [
        {
          key: 'include',
          test: 'nonblank',
        },
      ],
      origin: 'git',
      reason: 'Export requires at least one inclusion pattern.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate_export.go',
    },
    {
      id: 'lfsMigrateExport.unknown-options',
      kind: 'unsupported',
      keys: ['above', 'top', 'unit', 'pointers', 'fixup'],
      origin: 'git',
      reason: 'These options do not exist for migrate export.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_migrate.go',
    },
  ],
  reset: [
    {
      id: 'reset.intent-to-add-mode',
      kind: 'conflicts',
      when: active('intentToAdd'),
      others: [
        equal('mode', 'soft'),
        equal('mode', 'hard'),
        equal('mode', 'merge'),
        equal('mode', 'keep'),
      ],
      origin: 'git',
      reason: 'Intent-to-add requires mixed reset (the default mode).',
      source: 'https://github.com/git/git/blob/v2.55.0/builtin/reset.c',
    },
  ],
  stashPush: [
    {
      id: 'stashPush.staged',
      kind: 'conflicts',
      when: active('staged'),
      others: [active('includeUntracked'), active('all'), present('pathspecFromFile')],
      origin: 'git',
      reason: 'Staged-only stash rejects untracked files, all files, and pathspec files.',
      source: 'https://github.com/git/git/blob/v2.55.0/builtin/stash.c',
    },
    {
      id: 'stashPush.pathspec',
      kind: 'conflicts',
      when: present('pathspecFromFile'),
      others: [{ key: 'paths', test: 'nonempty' }],
      origin: 'git',
      reason: 'Pathspec files cannot be combined with command-line pathspecs.',
      source: 'https://github.com/git/git/blob/v2.55.0/builtin/stash.c',
    },
  ],
  tagCreate: [
    {
      id: 'tagCreate.message-file',
      kind: 'exclusive',
      keys: ['message', 'file'],
      origin: 'git',
      reason: 'Tag messages cannot come from both -m and -F.',
      source: 'https://github.com/git/git/blob/v2.55.0/builtin/tag.c',
    },
  ],
  submoduleUpdate: [
    {
      id: 'submoduleUpdate.filter-grammar',
      kind: 'scalar',
      key: 'filter',
      parser: 'object-filter',
      origin: 'git',
      reason: 'The object filter must use a supported Git filter grammar.',
      source: 'https://github.com/git/git/blob/v2.55.0/list-objects-filter-options.c',
    },
    {
      id: 'submoduleUpdate.filter-init',
      kind: 'requires',
      when: present('filter'),
      required: [active('init')],
      origin: 'git',
      reason: 'Submodule update filtering requires initialization.',
      source: 'https://github.com/git/git/blob/v2.55.0/builtin/submodule--helper.c',
    },
  ],
  remoteAdd: [
    {
      id: 'remoteAdd.push-mirror-track',
      kind: 'conflicts',
      when: equal('mirror', 'push'),
      others: [present('track')],
      origin: 'git',
      reason: 'Tracking branches is only supported for fetch mirrors.',
      source: 'https://github.com/git/git/blob/v2.55.0/builtin/remote.c',
    },
  ],
  lfsCheckout: [
    {
      id: 'lfsCheckout.stage',
      kind: 'exclusive',
      keys: ['base', 'ours', 'theirs'],
      origin: 'git',
      reason: 'Select at most one conflict stage.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_checkout.go',
    },
    {
      id: 'lfsCheckout.destination-stage',
      kind: 'requiresAny',
      when: { key: 'to', test: 'nonempty' },
      choices: [active('base'), active('ours'), active('theirs')],
      origin: 'git',
      reason: 'A conflict destination requires a conflict stage.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_checkout.go',
    },
    {
      id: 'lfsCheckout.base-destination',
      kind: 'requires',
      when: active('base'),
      required: [{ key: 'to', test: 'nonempty' }],
      origin: 'git',
      reason: 'A conflict stage requires a nonempty destination.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_checkout.go',
    },
    {
      id: 'lfsCheckout.ours-destination',
      kind: 'requires',
      when: active('ours'),
      required: [{ key: 'to', test: 'nonempty' }],
      origin: 'git',
      reason: 'A conflict stage requires a nonempty destination.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_checkout.go',
    },
    {
      id: 'lfsCheckout.theirs-destination',
      kind: 'requires',
      when: active('theirs'),
      required: [{ key: 'to', test: 'nonempty' }],
      origin: 'git',
      reason: 'A conflict stage requires a nonempty destination.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_checkout.go',
    },
    {
      id: 'lfsCheckout.unknown-options',
      kind: 'unsupported',
      keys: ['include', 'exclude'],
      origin: 'git',
      reason: 'LFS checkout has no include/exclude options; use positional patterns.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_checkout.go',
    },
  ],
  lfsLocks: [
    {
      id: 'lfsLocks.verify-limit',
      kind: 'range',
      key: 'limit',
      min: 0,
      when: active('verify'),
      origin: 'git',
      reason:
        'Lock verification allocates a result slice with this capacity and fails for negative limits.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/locking/locks.go',
    },
    {
      id: 'lfsLocks.limit-integer',
      kind: 'integer',
      key: 'limit',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason: 'Numeric CLI options use safe integers to prevent truncation and precision loss.',
      source: contract,
    },
    {
      id: 'lfsLocks.cached',
      kind: 'conflicts',
      when: active('cached'),
      others: [
        active('local'),
        { key: 'limit', test: 'positive' },
        { key: 'id', test: 'nonempty' },
        { key: 'path', test: 'nonempty' },
      ],
      origin: 'git',
      reason: 'Cached locks reject positive limits, filters, and local mode.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_locks.go',
    },
    {
      id: 'lfsLocks.verify',
      kind: 'conflicts',
      when: active('verify'),
      others: [active('local'), { key: 'id', test: 'nonempty' }, { key: 'path', test: 'nonempty' }],
      origin: 'git',
      reason: 'Lock verification rejects filters and local mode.',
      source: 'https://github.com/git-lfs/git-lfs/blob/v3.8.0/commands/command_locks.go',
    },
  ],
  clone: [
    {
      id: 'clone.filter-grammar',
      kind: 'scalar',
      key: 'filter',
      parser: 'object-filter-auto',
      origin: 'git',
      reason: 'The object filter must use a supported Git filter grammar.',
      source: 'https://github.com/git/git/blob/v2.55.0/list-objects-filter-options.c',
    },
    {
      id: 'clone.bare-separateGitDir',
      kind: 'exclusive',
      keys: ['bare', 'separateGitDir'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/clone.c'),
    },
    {
      id: 'clone.mirror-separateGitDir',
      kind: 'exclusive',
      keys: ['mirror', 'separateGitDir'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/clone.c'),
    },
    {
      id: 'clone.submodule-filter',
      kind: 'requires',
      when: active('alsoFilterSubmodules'),
      required: [active('filter'), active('recurseSubmodules')],
      origin: 'git',
      reason:
        'Explicit submodule filtering requires a filter and recursive submodule initialization.',
      source: git('builtin/clone.c'),
    },
    {
      id: 'clone.depth',
      kind: 'integer',
      key: 'depth',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason:
        'Numeric options use safe integers to avoid fractional truncation or loss of precision.',
      source: contract,
    },
    {
      id: 'clone.depth-range',
      kind: 'scalar',
      key: 'depth',
      parser: 'depth-initial',
      origin: 'git',
      reason: 'The final depth must be positive after Git converts it with atoi.',
      source: 'https://github.com/git/git/blob/v2.55.0/builtin/clone.c',
    },
    {
      id: 'clone.jobs',
      kind: 'integer',
      key: 'jobs',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason:
        'Numeric options use safe integers to avoid fractional truncation or loss of precision.',
      source: contract,
    },
  ],
  init: [
    {
      id: 'init.bare-separateGitDir',
      kind: 'exclusive',
      keys: ['bare', 'separateGitDir'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/init-db.c'),
    },
  ],
  lsRemote: [
    {
      id: 'lsRemote.unsupported',
      kind: 'unsupported',
      keys: ['getUrl', 'symref'],
      origin: 'type-git',
      reason: 'The ref-list result cannot represent URL-only output or symbolic-ref records.',
      source: contract,
    },
  ],
  lsTree: [
    {
      id: 'lsTree.nameOnly-objectOnly-long',
      kind: 'exclusive',
      keys: ['nameOnly', 'objectOnly', 'long'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/ls-tree.c'),
    },
    {
      id: 'lsTree.abbrev',
      kind: 'integer',
      key: 'abbrev',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason:
        'Numeric options use safe integers to avoid fractional truncation or loss of precision.',
      source: contract,
    },
  ],
  status: [
    {
      id: 'status.unsupported',
      kind: 'unsupported',
      keys: ['verbose'],
      origin: 'type-git',
      reason: 'The status result contains porcelain entries, not verbose patch output.',
      source: contract,
    },
    {
      id: 'status.porcelain',
      kind: 'value',
      key: 'porcelain',
      allowed: [2],
      origin: 'type-git',
      reason: 'The typed status parser reads porcelain v2.',
      source: contract,
    },
    {
      id: 'status.nul',
      kind: 'value',
      key: 'nullTerminated',
      allowed: [true],
      origin: 'type-git',
      reason: 'Structured paths use NUL delimiters to preserve all filenames.',
      source: contract,
    },
  ],
  log: [
    {
      id: 'log.unsupported',
      kind: 'unsupported',
      keys: [
        'source',
        'decorate',
        'decorateRefs',
        'decorateRefsExclude',
        'stat',
        'shortstat',
        'nameOnly',
        'nameStatus',
      ],
      origin: 'type-git',
      reason: 'The commit result has no fields for decorations, patches, or file statistics.',
      source: contract,
    },
    {
      id: 'log.maxCount',
      kind: 'integer',
      key: 'maxCount',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason:
        'Numeric options use safe integers to avoid fractional truncation or loss of precision.',
      source: contract,
    },
    {
      id: 'log.skip',
      kind: 'integer',
      key: 'skip',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason:
        'Numeric options use safe integers to avoid fractional truncation or loss of precision.',
      source: contract,
    },
  ],
  fetch: [
    {
      id: 'fetch.depth-unshallow',
      kind: 'exclusive',
      keys: ['depth', 'unshallow'],
      origin: 'git',
      reason: 'Unshallow cannot use an explicit depth.',
      source: git('builtin/fetch.c'),
    },
    {
      id: 'fetch.deepen-depth',
      kind: 'forbid',
      when: [{ key: 'deepen', test: 'nonzero' }, present('depth')],
      origin: 'git',
      reason: 'A nonzero deepen value cannot be combined with depth.',
      source: git('builtin/fetch.c'),
    },
    {
      id: 'fetch.deepen-unshallow',
      kind: 'forbid',
      when: [{ key: 'deepen', test: 'nonzero' }, active('unshallow')],
      origin: 'git',
      reason: 'A nonzero deepen value cannot be combined with unshallow.',
      source: git('builtin/fetch.c'),
    },
    {
      id: 'fetch.all-remote',
      kind: 'exclusive',
      keys: ['all', 'remote'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/fetch.c'),
    },
    {
      id: 'fetch.all-refspec',
      kind: 'exclusive',
      keys: ['all', 'refspec'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/fetch.c'),
    },
    {
      id: 'fetch.unsupported',
      kind: 'unsupported',
      keys: ['multiple'],
      origin: 'type-git',
      reason: 'The single-remote API has no multiple-remote operand list.',
      source: contract,
    },
    {
      id: 'fetch.depth',
      kind: 'integer',
      key: 'depth',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason:
        'Numeric options use safe integers to avoid fractional truncation or loss of precision.',
      source: contract,
    },
    {
      id: 'fetch.depth-range',
      kind: 'scalar',
      key: 'depth',
      parser: 'depth-initial',
      origin: 'git',
      reason: 'The final depth must be positive after Git converts it with atoi.',
      source: 'https://github.com/git/git/blob/v2.55.0/builtin/fetch.c',
    },
    {
      id: 'fetch.jobs',
      kind: 'integer',
      key: 'jobs',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason:
        'Numeric options use safe integers to avoid fractional truncation or loss of precision.',
      source: contract,
    },
    {
      id: 'fetch.deepen',
      kind: 'integer',
      key: 'deepen',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason:
        'Numeric options use safe integers to avoid fractional truncation or loss of precision.',
      source: contract,
    },
    {
      id: 'fetch.deepen-range',
      kind: 'range',
      key: 'deepen',
      min: 0,
      origin: 'git',
      reason: 'Git rejects values below 0 for deepen.',
      source: git('builtin/fetch.c'),
    },
  ],
  push: [
    {
      id: 'push.all-mirror-refspec',
      kind: 'exclusive',
      keys: ['all', 'mirror', 'refspec'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/push.c'),
    },
    {
      id: 'push.all-tags',
      kind: 'exclusive',
      keys: ['all', 'tags'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/push.c'),
    },
    {
      id: 'push.branches-mirror-refspec',
      kind: 'exclusive',
      keys: ['branches', 'mirror', 'refspec'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/push.c'),
    },
    {
      id: 'push.branches-tags',
      kind: 'exclusive',
      keys: ['branches', 'tags'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/push.c'),
    },
    {
      id: 'push.mirror-tags',
      kind: 'exclusive',
      keys: ['mirror', 'tags'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/push.c'),
    },
    {
      id: 'push.delete-all',
      kind: 'exclusive',
      keys: ['deleteRefs', 'all'],
      origin: 'git',
      reason: 'Delete mode cannot be combined with bulk push modes.',
      source: git('builtin/push.c'),
    },
    {
      id: 'push.delete-branches',
      kind: 'exclusive',
      keys: ['deleteRefs', 'branches'],
      origin: 'git',
      reason: 'Delete mode cannot be combined with bulk push modes.',
      source: git('builtin/push.c'),
    },
    {
      id: 'push.delete-mirror',
      kind: 'exclusive',
      keys: ['deleteRefs', 'mirror'],
      origin: 'git',
      reason: 'Delete mode cannot be combined with bulk push modes.',
      source: git('builtin/push.c'),
    },
    {
      id: 'push.delete-tags',
      kind: 'exclusive',
      keys: ['deleteRefs', 'tags'],
      origin: 'git',
      reason: 'Delete mode cannot be combined with bulk push modes.',
      source: git('builtin/push.c'),
    },
    {
      id: 'push.delete-refs',
      kind: 'requires',
      when: active('deleteRefs'),
      required: [active('refspec')],
      origin: 'git',
      reason: 'Deletion requires explicit refs.',
      source: git('builtin/push.c'),
    },
  ],
  add: [
    {
      id: 'add.all-update',
      kind: 'exclusive',
      keys: ['all', 'update'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/add.c'),
    },
    {
      id: 'add.unsupported',
      kind: 'unsupported',
      keys: ['interactive', 'patch'],
      origin: 'type-git',
      reason: 'Interactive patch selection requires a terminal protocol absent from this API.',
      source: contract,
    },
  ],
  checkoutBranch: [
    {
      id: 'checkoutBranch.createBranch-forceCreateBranch-detach-orphan',
      kind: 'exclusive',
      keys: ['createBranch', 'forceCreateBranch', 'detach', 'orphan'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/checkout.c'),
    },
  ],
  checkoutPath: [
    {
      id: 'checkoutPath.source-ours',
      kind: 'exclusive',
      keys: ['source', 'ours'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/checkout.c'),
    },
    {
      id: 'checkoutPath.source-theirs',
      kind: 'exclusive',
      keys: ['source', 'theirs'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/checkout.c'),
    },
  ],
  commit: [
    {
      id: 'commit.message-file-reuseMessage',
      kind: 'exclusive',
      keys: ['message', 'file', 'reuseMessage'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/commit.c'),
    },
    {
      id: 'commit.fixup-squash',
      kind: 'exclusive',
      keys: ['fixup', 'squash'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/commit.c'),
    },
    {
      id: 'commit.include-only-all',
      kind: 'exclusive',
      keys: ['include', 'only', 'all'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/commit.c'),
    },
    {
      id: 'commit.unsupported',
      kind: 'unsupported',
      keys: ['dryRun', 'reeditMessage'],
      origin: 'type-git',
      reason: 'The commit result requires a completed commit; editor interaction is not supported.',
      source: contract,
    },
    {
      id: 'commit.fixup-message-source',
      kind: 'exclusive',
      keys: ['reuseMessage', 'file', 'fixup'],
      origin: 'git',
      reason: 'Git rejects combining these message sources.',
      source: git('builtin/commit.c'),
    },
    {
      id: 'commit.author-reset',
      kind: 'exclusive',
      keys: ['author', 'resetAuthor'],
      origin: 'git',
      reason: 'An explicit author cannot be combined with resetting authorship.',
      source: git('builtin/commit.c'),
    },
    {
      id: 'commit.all-pathspec-file',
      kind: 'exclusive',
      keys: ['all', 'pathspecFromFile'],
      origin: 'git',
      reason: 'Commit --all cannot use a pathspec file.',
      source: git('builtin/commit.c'),
    },
  ],
  diff: [
    {
      id: 'diff.nameOnly-nameStatus',
      kind: 'exclusive',
      keys: ['nameOnly', 'nameStatus'],
      origin: 'git',
      reason: 'Git rejects simultaneous name-only and name-status output.',
      source: git('diff.c'),
    },
    {
      id: 'diff.unsupported',
      kind: 'unsupported',
      keys: ['noIndex'],
      origin: 'type-git',
      reason: 'The repository diff API has no pair of filesystem operands for --no-index.',
      source: contract,
    },
    {
      id: 'diff.nul',
      kind: 'value',
      key: 'nullTerminated',
      allowed: [true],
      origin: 'type-git',
      reason: 'Structured paths use NUL delimiters to preserve all filenames.',
      source: contract,
    },
    {
      id: 'diff.context',
      kind: 'integer',
      key: 'context',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason:
        'Numeric options use safe integers to avoid fractional truncation or loss of precision.',
      source: contract,
    },
    {
      id: 'diff.context-range',
      kind: 'range',
      key: 'context',
      min: 0,
      origin: 'git',
      reason: 'Git rejects values below 0 for context.',
      source: git('diff.c'),
    },
    {
      id: 'diff.renameLimit',
      kind: 'integer',
      key: 'renameLimit',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason:
        'Numeric options use safe integers to avoid fractional truncation or loss of precision.',
      source: contract,
    },
    {
      id: 'diff.abbrev',
      kind: 'integer',
      key: 'abbrev',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason:
        'Numeric options use safe integers to avoid fractional truncation or loss of precision.',
      source: contract,
    },
  ],
  merge: [
    {
      id: 'merge.abort-continue-quit',
      kind: 'exclusive',
      keys: ['abort', 'continue', 'quit'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/merge.c'),
    },
    {
      id: 'merge.abort-options',
      kind: 'conflicts',
      when: active('abort'),
      others: [
        active('message'),
        present('ff'),
        active('squash'),
        active('noCommit'),
        active('strategy'),
        active('strategyOption'),
        active('noVerify'),
        active('noDiffstat'),
        active('stat'),
        active('compactSummary'),
        active('log'),
        active('cleanup'),
        present('rerereAutoupdate'),
        active('verifySignatures'),
        active('verbose'),
        active('quiet'),
        active('allowUnrelatedHistories'),
        active('gpgSign'),
        present('autostash'),
        present('overwriteIgnore'),
        active('signoff'),
        active('intoName'),
      ],
      origin: 'git',
      reason: 'Merge control operations accept no additional command arguments.',
      source: git('builtin/merge.c'),
    },
    {
      id: 'merge.continue-options',
      kind: 'conflicts',
      when: active('continue'),
      others: [
        active('message'),
        present('ff'),
        active('squash'),
        active('noCommit'),
        active('strategy'),
        active('strategyOption'),
        active('noVerify'),
        active('noDiffstat'),
        active('stat'),
        active('compactSummary'),
        active('log'),
        active('cleanup'),
        present('rerereAutoupdate'),
        active('verifySignatures'),
        active('verbose'),
        active('quiet'),
        active('allowUnrelatedHistories'),
        active('gpgSign'),
        present('autostash'),
        present('overwriteIgnore'),
        active('signoff'),
        active('intoName'),
      ],
      origin: 'git',
      reason: 'Merge control operations accept no additional command arguments.',
      source: git('builtin/merge.c'),
    },
    {
      id: 'merge.quit-options',
      kind: 'conflicts',
      when: active('quit'),
      others: [
        active('message'),
        present('ff'),
        active('squash'),
        active('noCommit'),
        active('strategy'),
        active('strategyOption'),
        active('noVerify'),
        active('noDiffstat'),
        active('stat'),
        active('compactSummary'),
        active('log'),
        active('cleanup'),
        present('rerereAutoupdate'),
        active('verifySignatures'),
        active('verbose'),
        active('quiet'),
        active('allowUnrelatedHistories'),
        active('gpgSign'),
        present('autostash'),
        present('overwriteIgnore'),
        active('signoff'),
        active('intoName'),
      ],
      origin: 'git',
      reason: 'Merge control operations accept no additional command arguments.',
      source: git('builtin/merge.c'),
    },
    {
      id: 'merge.squash-no-ff-no',
      kind: 'forbid',
      when: [active('squash'), equal('ff', 'no')],
      origin: 'git',
      reason: 'Squashing is incompatible with explicitly disabling fast-forward.',
      source: git('builtin/merge.c'),
    },
    {
      id: 'merge.squash-no-ff-false',
      kind: 'forbid',
      when: [active('squash'), equal('ff', false)],
      origin: 'git',
      reason: 'Squashing is incompatible with explicitly disabling fast-forward.',
      source: git('builtin/merge.c'),
    },
  ],
  pull: [
    {
      id: 'pull.depth-unshallow',
      kind: 'exclusive',
      keys: ['depth', 'unshallow'],
      origin: 'git',
      reason: 'Unshallow cannot use an explicit depth.',
      source: git('builtin/fetch.c'),
    },
    {
      id: 'pull.deepen-depth',
      kind: 'forbid',
      when: [{ key: 'deepen', test: 'nonzero' }, present('depth')],
      origin: 'git',
      reason: 'A nonzero deepen value cannot be combined with depth.',
      source: git('builtin/fetch.c'),
    },
    {
      id: 'pull.deepen-unshallow',
      kind: 'forbid',
      when: [{ key: 'deepen', test: 'nonzero' }, active('unshallow')],
      origin: 'git',
      reason: 'A nonzero deepen value cannot be combined with unshallow.',
      source: git('builtin/fetch.c'),
    },
    {
      id: 'pull.depth',
      kind: 'integer',
      key: 'depth',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason:
        'Numeric options use safe integers to avoid fractional truncation or loss of precision.',
      source: contract,
    },
    {
      id: 'pull.depth-range',
      kind: 'range',
      key: 'depth',
      min: 1,
      origin: 'git',
      reason: 'Git rejects values below 1 for depth.',
      source: git('builtin/pull.c'),
    },
    {
      id: 'pull.jobs',
      kind: 'integer',
      key: 'jobs',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason:
        'Numeric options use safe integers to avoid fractional truncation or loss of precision.',
      source: contract,
    },
    {
      id: 'pull.deepen',
      kind: 'integer',
      key: 'deepen',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason:
        'Numeric options use safe integers to avoid fractional truncation or loss of precision.',
      source: contract,
    },
    {
      id: 'pull.deepen-range',
      kind: 'range',
      key: 'deepen',
      min: 0,
      origin: 'git',
      reason: 'Git rejects values below 0 for deepen.',
      source: git('builtin/pull.c'),
    },
  ],
  switch: [
    {
      id: 'switch.create-forceCreate-detach-orphan',
      kind: 'exclusive',
      keys: ['create', 'forceCreate', 'detach', 'orphan'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/checkout.c'),
    },
    {
      id: 'switch.discard-merge',
      kind: 'exclusive',
      keys: ['discard', 'merge'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/checkout.c'),
    },
    {
      id: 'switch.force-merge',
      kind: 'exclusive',
      keys: ['force', 'merge'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/checkout.c'),
    },
  ],
  cherryPick: [
    {
      id: 'cherryPick.abort-continue-skip',
      kind: 'exclusive',
      keys: ['abort', 'continue', 'skip'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/revert.c'),
    },
    {
      id: 'cherryPick.unsupported',
      kind: 'unsupported',
      keys: ['noVerify'],
      origin: 'git',
      reason: 'These options are absent from the command syntax.',
      source: git('builtin/revert.c'),
    },
    {
      id: 'cherryPick.mainline',
      kind: 'integer',
      key: 'mainline',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason:
        'Numeric options use safe integers to avoid fractional truncation or loss of precision.',
      source: contract,
    },
    {
      id: 'cherryPick.mainline-range',
      kind: 'scalar',
      key: 'mainline',
      parser: NUMERIC_CALLBACK_PARSERS.mainline,
      origin: 'git',
      reason:
        'Git requires a positive mainline after decimal strtol conversion and narrowing to int.',
      source: 'https://github.com/git/git/blob/v2.55.0/builtin/revert.c',
    },
    {
      id: 'cherryPick.abort-options',
      kind: 'conflicts',
      when: active('abort'),
      others: [
        active('noCommit'),
        active('signoff'),
        active('mainline'),
        active('strategy'),
        active('strategyOption'),
        active('appendCommitName'),
        active('ff'),
        active('empty'),
        present('rerereAutoupdate'),
      ],
      origin: 'git',
      reason: 'The sequencer rejects this option with a control operation.',
      source: git('builtin/revert.c'),
    },
    {
      id: 'cherryPick.continue-options',
      kind: 'conflicts',
      when: active('continue'),
      others: [
        active('noCommit'),
        active('signoff'),
        active('mainline'),
        active('strategy'),
        active('strategyOption'),
        active('appendCommitName'),
        active('ff'),
        active('empty'),
        present('rerereAutoupdate'),
      ],
      origin: 'git',
      reason: 'The sequencer rejects this option with a control operation.',
      source: git('builtin/revert.c'),
    },
    {
      id: 'cherryPick.skip-options',
      kind: 'conflicts',
      when: active('skip'),
      others: [
        active('noCommit'),
        active('signoff'),
        active('mainline'),
        active('strategy'),
        active('strategyOption'),
        active('appendCommitName'),
        active('ff'),
        active('empty'),
        present('rerereAutoupdate'),
      ],
      origin: 'git',
      reason: 'The sequencer rejects this option with a control operation.',
      source: git('builtin/revert.c'),
    },
    {
      id: 'cherryPick.ff-signoff',
      kind: 'exclusive',
      keys: ['ff', 'signoff'],
      origin: 'git',
      reason: 'Fast-forward cherry-picks reject this commit modification option.',
      source: git('builtin/revert.c'),
    },
    {
      id: 'cherryPick.ff-noCommit',
      kind: 'exclusive',
      keys: ['ff', 'noCommit'],
      origin: 'git',
      reason: 'Fast-forward cherry-picks reject this commit modification option.',
      source: git('builtin/revert.c'),
    },
    {
      id: 'cherryPick.ff-appendCommitName',
      kind: 'exclusive',
      keys: ['ff', 'appendCommitName'],
      origin: 'git',
      reason: 'Fast-forward cherry-picks reject this commit modification option.',
      source: git('builtin/revert.c'),
    },
    {
      id: 'cherryPick.ff-edit',
      kind: 'exclusive',
      keys: ['ff', 'edit'],
      origin: 'git',
      reason: 'Fast-forward cherry-picks reject this commit modification option.',
      source: git('builtin/revert.c'),
    },
  ],
  revert: [
    {
      id: 'revert.abort-continue-skip',
      kind: 'exclusive',
      keys: ['abort', 'continue', 'skip'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/revert.c'),
    },
    {
      id: 'revert.unsupported',
      kind: 'unsupported',
      keys: ['noVerify'],
      origin: 'git',
      reason: 'These options are absent from the command syntax.',
      source: git('builtin/revert.c'),
    },
    {
      id: 'revert.mainline',
      kind: 'integer',
      key: 'mainline',
      min: Number.MIN_SAFE_INTEGER,
      origin: 'type-git',
      reason:
        'Numeric options use safe integers to avoid fractional truncation or loss of precision.',
      source: contract,
    },
    {
      id: 'revert.mainline-range',
      kind: 'scalar',
      key: 'mainline',
      parser: NUMERIC_CALLBACK_PARSERS.mainline,
      origin: 'git',
      reason:
        'Git requires a positive mainline after decimal strtol conversion and narrowing to int.',
      source: 'https://github.com/git/git/blob/v2.55.0/builtin/revert.c',
    },
    {
      id: 'revert.abort-options',
      kind: 'conflicts',
      when: active('abort'),
      others: [
        active('noCommit'),
        active('signoff'),
        active('mainline'),
        active('strategy'),
        active('strategyOption'),
        present('rerereAutoupdate'),
      ],
      origin: 'git',
      reason: 'The sequencer rejects this option with a control operation.',
      source: git('builtin/revert.c'),
    },
    {
      id: 'revert.continue-options',
      kind: 'conflicts',
      when: active('continue'),
      others: [
        active('noCommit'),
        active('signoff'),
        active('mainline'),
        active('strategy'),
        active('strategyOption'),
        present('rerereAutoupdate'),
      ],
      origin: 'git',
      reason: 'The sequencer rejects this option with a control operation.',
      source: git('builtin/revert.c'),
    },
    {
      id: 'revert.skip-options',
      kind: 'conflicts',
      when: active('skip'),
      others: [
        active('noCommit'),
        active('signoff'),
        active('mainline'),
        active('strategy'),
        active('strategyOption'),
        present('rerereAutoupdate'),
      ],
      origin: 'git',
      reason: 'The sequencer rejects this option with a control operation.',
      source: git('builtin/revert.c'),
    },
  ],
  rebase: [
    {
      id: 'rebase.abort-continue-skip',
      kind: 'exclusive',
      keys: ['abort', 'continue', 'skip'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/rebase.c'),
    },
    {
      id: 'rebase.keepBase-onto',
      kind: 'exclusive',
      keys: ['keepBase', 'onto'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/rebase.c'),
    },
    {
      id: 'rebase.keepBase-root',
      kind: 'exclusive',
      keys: ['keepBase', 'root'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/rebase.c'),
    },
    {
      id: 'rebase.apply-rebaseMerges',
      kind: 'exclusive',
      keys: ['apply', 'rebaseMerges'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/rebase.c'),
    },
    {
      id: 'rebase.apply-strategy',
      kind: 'exclusive',
      keys: ['apply', 'strategy'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/rebase.c'),
    },
    {
      id: 'rebase.apply-exec',
      kind: 'exclusive',
      keys: ['apply', 'exec'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/rebase.c'),
    },
    {
      id: 'rebase.unsupported',
      kind: 'unsupported',
      keys: ['interactive'],
      origin: 'type-git',
      reason: 'Interactive todo editing requires an editor protocol absent from this API.',
      source: contract,
    },
    {
      id: 'rebase.root-forkPoint',
      kind: 'exclusive',
      keys: ['root', 'forkPoint'],
      origin: 'git',
      reason: 'Root rebases cannot use fork-point detection.',
      source: git('builtin/rebase.c'),
    },
  ],
  restore: [
    {
      id: 'restore.staged-conflict',
      kind: 'conflicts',
      when: active('staged'),
      others: [active('ours'), active('theirs'), active('merge'), active('conflict')],
      origin: 'git',
      reason: 'Git rejects index-stage and conflict recreation modes with --staged.',
      source: git('builtin/checkout.c'),
    },
    {
      id: 'restore.source-ours',
      kind: 'exclusive',
      keys: ['source', 'ours'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/checkout.c'),
    },
    {
      id: 'restore.source-theirs',
      kind: 'exclusive',
      keys: ['source', 'theirs'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/checkout.c'),
    },
    {
      id: 'restore.source-merge',
      kind: 'exclusive',
      keys: ['source', 'merge'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/checkout.c'),
    },
    {
      id: 'restore.source-conflict',
      kind: 'exclusive',
      keys: ['source', 'conflict'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/checkout.c'),
    },
  ],
  clean: [
    {
      id: 'clean.ignored-onlyIgnored',
      kind: 'exclusive',
      keys: ['ignored', 'onlyIgnored'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/clean.c'),
    },
  ],
  worktreeAdd: [
    {
      id: 'worktreeAdd.branch-detach',
      kind: 'exclusive',
      keys: ['branch', 'detach'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/worktree.c'),
    },
    {
      id: 'worktreeAdd.orphan-detach',
      kind: 'exclusive',
      keys: ['orphan', 'detach'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/worktree.c'),
    },
    {
      id: 'worktreeAdd.orphan-track',
      kind: 'exclusive',
      keys: ['orphan', 'track'],
      origin: 'git',
      reason: 'An orphan worktree cannot track another branch.',
      source: git('builtin/worktree.c'),
    },
    {
      id: 'worktreeAdd.orphan-commitish',
      kind: 'exclusive',
      keys: ['orphan', 'commitish'],
      origin: 'git',
      reason: 'An orphan worktree cannot take a commit-ish.',
      source: git('builtin/worktree.c'),
    },
    {
      id: 'worktreeAdd.orphan-no-checkout',
      kind: 'forbid',
      when: [active('orphan'), equal('checkout', false)],
      origin: 'git',
      reason: 'An orphan worktree cannot disable checkout.',
      source: git('builtin/worktree.c'),
    },
  ],
  remoteSetHead: [
    {
      id: 'remoteSetHead.auto-delete',
      kind: 'exclusive',
      keys: ['auto', 'delete'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/remote.c'),
    },
  ],
  configGet: [
    {
      id: 'configGet.all-default',
      kind: 'exclusive',
      keys: ['all', 'default'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: git('builtin/config.c'),
    },
  ],
  configList: [
    {
      id: 'configList.unsupported',
      kind: 'unsupported',
      keys: ['nameOnly'],
      origin: 'type-git',
      reason: 'Config entries require values; names-only output does not provide them.',
      source: contract,
    },
  ],
  lfsPull: [
    {
      id: 'lfsPull.unsupported',
      kind: 'unsupported',
      keys: ['ref'],
      origin: 'git',
      reason: 'These options are absent from the command syntax.',
      source: lfs('pull'),
    },
  ],
  lfsPush: [
    {
      id: 'lfsPush.ref-objectId',
      kind: 'exclusive',
      keys: ['ref', 'objectId'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: lfs('push'),
    },
  ],
  lfsFetch: [
    {
      id: 'lfsFetch.all-include',
      kind: 'exclusive',
      keys: ['all', 'include'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: lfs('fetch'),
    },
    {
      id: 'lfsFetch.all-exclude',
      kind: 'exclusive',
      keys: ['all', 'exclude'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: lfs('fetch'),
    },
    {
      id: 'lfsFetch.all-recent',
      kind: 'exclusive',
      keys: ['all', 'recent'],
      origin: 'git',
      reason: 'Git rejects these simultaneous modes or operands.',
      source: lfs('fetch'),
    },
  ],
  lfsStatus: [
    {
      id: 'lfsStatus.unsupported',
      kind: 'unsupported',
      keys: ['porcelain'],
      origin: 'type-git',
      reason: 'LFS status metadata is parsed from JSON.',
      source: contract,
    },
    {
      id: 'lfsStatus.json',
      kind: 'value',
      key: 'json',
      allowed: [true],
      origin: 'type-git',
      reason: 'Structured LFS metadata is parsed from JSON.',
      source: contract,
    },
  ],
  lfsLsFiles: [
    {
      id: 'lfsLsFiles.unsupported',
      kind: 'unsupported',
      keys: ['debug', 'nameOnly'],
      origin: 'type-git',
      reason: 'LFS file metadata requires JSON records with object IDs and sizes.',
      source: contract,
    },
    {
      id: 'lfsLsFiles.json',
      kind: 'value',
      key: 'json',
      allowed: [true],
      origin: 'type-git',
      reason: 'Structured LFS metadata is parsed from JSON.',
      source: contract,
    },
  ],
} as const satisfies Record<string, readonly Constraint[]>;

export type CommandName = keyof typeof COMMAND_CONSTRAINTS;
