// Generated by node scripts/compound-decimals.mjs. Do not edit.
import type { CompoundDecimalProfile } from './compound-decimal.js';
export const COMPOUND_DECIMALS = {
  'shortlog-wrap': {
    kind: 'tuple',
    separator: ',',
    decimal: {
      kind: 'decimal',
      longBits: 64,
      bits: 32,
      signed: true,
      unsignedLong: true,
      conversion: 'checked',
    },
    defaults: [76, 6, 9],
    nonzeroGreaterThan: {
      index: 0,
      others: [1, 2],
    },
    source: 'builtin/shortlog.c:parse_uint/parse_wrap_args',
  },
  'show-branch-reflog': {
    kind: 'prefix',
    separator: ',',
    decimal: {
      kind: 'decimal',
      longBits: 64,
      bits: 32,
      signed: true,
      unsignedLong: true,
      conversion: 'cast',
      empty: true,
    },
    source: 'builtin/show-branch.c:parse_reflog_param',
  },
} as const satisfies Record<string, CompoundDecimalProfile>;
