// Generated by node scripts/string-callbacks.mjs. Do not edit.
import type { StringCallbackProfile } from './string-callback.js';
export const STRING_CALLBACKS = {
  'anonymize-map': {
    kind: 'first-separator',
    separator: ':',
    allowUnseparated: true,
    source:
      'builtin/fast-export.c:parse_opt_anonymize_map; both sides of the first separator must be nonempty',
  },
  'fast-import-sign': {
    kind: 'choice',
    exact: [
      'abort',
      'verbatim',
      'ignore',
      'warn-verbatim',
      'warn',
      'warn-strip',
      'strip',
      'abort-if-invalid',
      'strip-if-invalid',
      'sign-if-invalid',
    ],
    prefixes: ['sign-if-invalid='],
    source:
      'gpg-interface.c:parse_sign_mode; builtin/fast-import.c:parse_one_option; a key suffix may be empty',
  },
  'column-mode': {
    kind: 'token-list',
    separators: [' ', ','],
    exact: ['always', 'never', 'auto', 'plain', 'column', 'row', 'dense', 'nodense'],
    projection: {
      initial: 'always',
      values: {
        always: 'always',
        never: 'never',
        auto: 'auto',
      },
    },
    source:
      'column.c:parse_config/parse_option/parseopt_column_callback; enable projection only; auto depends on tty/pager during finalization',
  },
} as const satisfies Record<string, StringCallbackProfile>;
