import ts from 'typescript';
import { optionDomains, literal, compilerRules } from './constraint-domains.mjs';
import { mkdtemp, readFile, writeFile, rm, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';

// Build tooling only. Runtime consumers never load the compiler or the explorer.
const root = fileURLToPath(new URL('../', import.meta.url));
const scratch = await mkdtemp(join(tmpdir(), 'type-git-constraints-'));
try {
  await writeFile(join(scratch, 'package.json'), '{"type":"module"}');
  for (const name of ['model', 'commands', 'explore', 'clone-domains', 'decision-diagram', 'scalars', 'git-scalars', 'object-filter', 'inputs']) {
    const source = await readFile(join(root, `src/constraints/${name}.ts`), 'utf8');
    const { outputText } = ts.transpileModule(source, {
      compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext },
    });
    await writeFile(join(scratch, `${name}.js`), outputText);
  }
  const { COMMAND_CONSTRAINTS } = await import(pathToFileURL(join(scratch, 'commands.js')));
  const { CLONE_DOMAINS } = await import(pathToFileURL(join(scratch, 'clone-domains.js')));
  const { explore } = await import(pathToFileURL(join(scratch, 'explore.js')));
  const { violations, referencedKeys } = await import(pathToFileURL(join(scratch, 'model.js')));
  // Every rule key must name an actual option. Never silently drop misspelled keys
  // when projecting the schema onto TypeScript types.
  const { solve } = await import(pathToFileURL(join(scratch, 'decision-diagram.js')));
  const checkedCommands = new Set();
  const aliases = new Map();
  const declarations = [];
  const sources = [];
  for (const file of ['src/core/git.ts', 'src/core/repo.ts']) {
    const source = ts.createSourceFile(file, await readFile(join(root, file), 'utf8'), ts.ScriptTarget.Latest, true);
    sources.push({ file, source });
    for (const declaration of source.statements) {
      if (ts.isTypeAliasDeclaration(declaration)) aliases.set(declaration.name.text, declaration.type);
    }
  }

  for (const { file, source } of sources) {
    for (const declaration of source.statements) {
      if (!ts.isTypeAliasDeclaration(declaration) || !ts.isTypeReferenceNode(declaration.type)) continue;
      if (declaration.type.typeName.getText(source) !== 'CheckedOptions') continue;
      const [options, name] = declaration.type.typeArguments;
      if (!ts.isTypeLiteralNode(options) || !ts.isLiteralTypeNode(name) || !ts.isStringLiteral(name.literal)) {
        throw new Error(`Unrecognized CheckedOptions declaration: ${declaration.name.text}`);
      }
      const command = name.literal.text;
      const keys = new Set(options.members.map((member) => member.name?.getText(source)));
      if (!(command in COMMAND_CONSTRAINTS)) throw new Error(`Missing command schema: ${command}`);
      for (const rule of COMMAND_CONSTRAINTS[command]) {
        for (const key of referencedKeys(rule)) {
          if (!keys.has(key)) throw new Error(`${rule.id}: unknown ${declaration.name.text} key ${key}`);
        }
      }
      checkedCommands.add(command);
      declarations.push({ command, name: declaration.name.text, file, domains: optionDomains(options, aliases, COMMAND_CONSTRAINTS[command]) });
    }
  }
  for (const command of Object.keys(COMMAND_CONSTRAINTS)) {
    if (!checkedCommands.has(command)) throw new Error(`No public option type for ${command}`);
  }
  const groups = explore(COMMAND_CONSTRAINTS.clone, CLONE_DOMAINS);
  const output = [
    '// Generated by pnpm constraints:generate. Do not edit.',
    "import type { CloneOpts } from '../../src/core/git.js';",
    '',
  ];
  let index = 0;
  for (const group of groups) {
    output.push(`// Component: ${group.keys.join(', ')}`);
    for (const { options } of group.cases) {
      const errors = violations(compilerRules(COMMAND_CONSTRAINTS.clone), options);
      if (errors.length) output.push(`// @ts-expect-error ${errors.map((r) => r.id).join(', ')}`);
      output.push(`export const case${index++}: CloneOpts = ${JSON.stringify(options)};`);
    }
  }
  const report = ['# Option constraint inventory', '',
    'Generated by `pnpm constraints:generate`. Sources identify the reviewed baseline; they do not prove completeness across Git versions.', '',
    `Clone: ${groups.length} independent components, ${index} exhaustively enumerated representative assignments. Numeric ranges and scalar grammars in non-generic option objects are runtime checks.`, '',
    '| Command | Rule | Origin | Condition | Reason / source |',
    '| --- | --- | --- | --- | --- |'];
  for (const [command, rules] of Object.entries(COMMAND_CONSTRAINTS)) {
    for (const { id, origin, reason, source, ...condition } of rules) {
      const target = source.startsWith('http') ? source : './option-constraints.md';
      report.push(`| ${command} | ${id} | ${origin} | \`${JSON.stringify(condition).replaceAll('|', '\\|')}\` | [${reason}](${target}) |`);
    }
  }
  const { INPUT_CONSTRAINTS, INPUT_DOMAINS } = await import(pathToFileURL(join(scratch, 'inputs.js')));
  const symbolic = Object.entries(INPUT_CONSTRAINTS).map(([command, rules]) => {
    const result = solve(rules, INPUT_DOMAINS[command]);
    return { command, scope: 'operands', total: String(result.total), accepted: String(result.accepted), nodes: result.nodes.length };
  });
  const compilerCases = ['// Generated by pnpm constraints:generate. Do not edit.'];
  let compilerIndex = 0;
  for (const { command, name, file, domains } of declarations) {
    compilerCases.push(`import type { ${name} } from '../../${file.replace(/\.ts$/, '.js')}';`);
    const result = solve(COMMAND_CONSTRAINTS[command], domains);
    symbolic.push({ command, type: name, domains: Object.fromEntries(Object.entries(domains).map(([key, values]) => [key, values.map(literal)])),
      total: String(result.total), accepted: String(result.accepted), nodes: result.nodes.length,
      isolatedRuleWitnesses: Object.fromEntries(Object.entries(result.counterexamples).map(([id, witness]) => [id, witness === undefined ? null : literal(witness)])),
    });
    if (result.accepted === 0n) throw new Error(`Unsatisfiable schema: ${name}`);
    const projected = solve(compilerRules(COMMAND_CONSTRAINTS[command]), domains);
    compilerCases.push(`export const witness${compilerIndex++}: ${name} = ${literal(projected.witness)};`);
    for (const [id, witness] of Object.entries(projected.counterexamples)) {
      if (witness === undefined) continue;
      compilerCases.push(`// @ts-expect-error ${id}`, `export const witness${compilerIndex++}: ${name} = ${literal(witness)};`);
    }
  }
  report.splice(4, 0, `All ${checkedCommands.size} modelled families also have exact finite-domain decision-diagram counts and isolated-rule witnesses in [constraint-exploration.json](./constraint-exploration.json). This is bounded model coverage, not upstream command coverage.`, '');
  const artifacts = [
    ['test/types/generated-command-constraints.ts', compilerCases.join('\n') + '\n'],
    ['docs/design/constraint-exploration.json', JSON.stringify(symbolic, null, 2) + '\n'],
    ['test/types/generated-clone-constraints.ts', output.join('\n') + '\n'],
    ['docs/design/option-constraint-inventory.md', report.join('\n') + '\n'],
  ];
  for (const [name, content] of artifacts) {
    const path = join(root, name);
    if (process.argv.includes('--check')) {
      if (await readFile(path, 'utf8').catch(() => '') !== content) {
        throw new Error(`${name} is stale; run pnpm constraints:generate`);
      }
    } else {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, content);
    }
  }
  console.log(`Constraint artifacts verified: ${groups.length} clone components, ${index} cases.`);
} finally {
  await rm(scratch, { recursive: true, force: true });
}
