import ts from 'typescript';
import { mkdtemp, readFile, writeFile, rm, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';

// Build tooling only. Runtime consumers never load the compiler or the explorer.
const root = fileURLToPath(new URL('../', import.meta.url));
const scratch = await mkdtemp(join(tmpdir(), 'type-git-constraints-'));
try {
  await writeFile(join(scratch, 'package.json'), '{"type":"module"}');
  for (const name of ['model', 'commands', 'explore', 'clone-domains']) {
    const source = await readFile(join(root, `src/constraints/${name}.ts`), 'utf8');
    const { outputText } = ts.transpileModule(source, {
      compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext },
    });
    await writeFile(join(scratch, `${name}.js`), outputText);
  }
  const { COMMAND_CONSTRAINTS } = await import(pathToFileURL(join(scratch, 'commands.js')));
  const { CLONE_DOMAINS } = await import(pathToFileURL(join(scratch, 'clone-domains.js')));
  const { explore } = await import(pathToFileURL(join(scratch, 'explore.js')));
  const { violations, referencedKeys } = await import(pathToFileURL(join(scratch, 'model.js')));
  // Every rule key must name an actual option. Never silently drop misspelled keys
  // when projecting the schema onto TypeScript types.
  const checkedCommands = new Set();
  for (const file of ['src/core/git.ts', 'src/core/repo.ts']) {
    const source = ts.createSourceFile(file, await readFile(join(root, file), 'utf8'), ts.ScriptTarget.Latest, true);
    for (const declaration of source.statements) {
      if (!ts.isTypeAliasDeclaration(declaration) || !ts.isTypeReferenceNode(declaration.type)) continue;
      if (declaration.type.typeName.getText(source) !== 'CheckedOptions') continue;
      const [options, name] = declaration.type.typeArguments;
      if (!ts.isTypeLiteralNode(options) || !ts.isLiteralTypeNode(name) || !ts.isStringLiteral(name.literal)) {
        throw new Error(`Unrecognized CheckedOptions declaration: ${declaration.name.text}`);
      }
      const command = name.literal.text;
      const keys = new Set(options.members.map((member) => member.name?.getText(source)));
      if (!(command in COMMAND_CONSTRAINTS)) throw new Error(`Missing command schema: ${command}`);
      for (const rule of COMMAND_CONSTRAINTS[command]) {
        for (const key of referencedKeys(rule)) {
          if (!keys.has(key)) throw new Error(`${rule.id}: unknown ${declaration.name.text} key ${key}`);
        }
      }
      checkedCommands.add(command);
    }
  }
  for (const command of Object.keys(COMMAND_CONSTRAINTS)) {
    if (!checkedCommands.has(command)) throw new Error(`No public option type for ${command}`);
  }
  const groups = explore(COMMAND_CONSTRAINTS.clone, CLONE_DOMAINS);
  const output = [
    '// Generated by pnpm constraints:generate. Do not edit.',
    "import type { CloneOpts } from '../../src/core/git.js';",
    '',
  ];
  let index = 0;
  for (const group of groups) {
    output.push(`// Component: ${group.keys.join(', ')}`);
    for (const { options } of group.cases) {
      const errors = violations(COMMAND_CONSTRAINTS.clone.filter((r) => r.kind !== 'integer' && r.kind !== 'range'), options);
      if (errors.length) output.push(`// @ts-expect-error ${errors.map((r) => r.id).join(', ')}`);
      output.push(`export const case${index++}: CloneOpts = ${JSON.stringify(options)};`);
    }
  }
  const report = ['# Option constraint inventory', '',
    'Generated by `pnpm constraints:generate`. Sources identify the reviewed baseline; they do not prove completeness across Git versions.', '',
    `Clone: ${groups.length} independent components, ${index} exhaustively enumerated representative assignments. Numeric ranges are runtime checks.`, '',
    '| Command | Rule | Origin | Condition | Reason / source |',
    '| --- | --- | --- | --- | --- |'];
  for (const [command, rules] of Object.entries(COMMAND_CONSTRAINTS)) {
    for (const { id, origin, reason, source, ...condition } of rules) {
      const target = source.startsWith('http') ? source : './option-constraints.md';
      report.push(`| ${command} | ${id} | ${origin} | \`${JSON.stringify(condition).replaceAll('|', '\\|')}\` | [${reason}](${target}) |`);
    }
  }
  const artifacts = [
    ['test/types/generated-clone-constraints.ts', output.join('\n') + '\n'],
    ['docs/design/option-constraint-inventory.md', report.join('\n') + '\n'],
  ];
  for (const [name, content] of artifacts) {
    const path = join(root, name);
    if (process.argv.includes('--check')) {
      if (await readFile(path, 'utf8').catch(() => '') !== content) {
        throw new Error(`${name} is stale; run pnpm constraints:generate`);
      }
    } else {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, content);
    }
  }
  console.log(`Constraint artifacts verified: ${groups.length} clone components, ${index} cases.`);
} finally {
  await rm(scratch, { recursive: true, force: true });
}
