// Generated by pnpm constraints:generate. Do not edit.
import type { CloneOpts } from '../../src/core/git.js';
export const witness0: CloneOpts = {};
// @ts-expect-error clone.bare-separateGitDir
export const witness1: CloneOpts = {"bare":true,"separateGitDir":""};
// @ts-expect-error clone.mirror-separateGitDir
export const witness2: CloneOpts = {"mirror":true,"separateGitDir":""};
// @ts-expect-error clone.submodule-filter
export const witness3: CloneOpts = {"alsoFilterSubmodules":true};
import type { InitOpts } from '../../src/core/git.js';
export const witness4: InitOpts = {};
// @ts-expect-error init.bare-separateGitDir
export const witness5: InitOpts = {"bare":true,"separateGitDir":""};
import type { LsRemoteOpts } from '../../src/core/git.js';
export const witness6: LsRemoteOpts = {};
// @ts-expect-error lsRemote.unsupported
export const witness7: LsRemoteOpts = {"symref":false};
import type { RepoLsRemoteOpts } from '../../src/core/repo.js';
export const witness8: RepoLsRemoteOpts = {};
// @ts-expect-error lsRemote.unsupported
export const witness9: RepoLsRemoteOpts = {"symref":false};
import type { LsTreeOpts } from '../../src/core/repo.js';
export const witness10: LsTreeOpts = {};
// @ts-expect-error lsTree.nameOnly-objectOnly-long
export const witness11: LsTreeOpts = {"nameOnly":true,"objectOnly":true};
import type { StatusOpts } from '../../src/core/repo.js';
export const witness12: StatusOpts = {};
// @ts-expect-error status.unsupported
export const witness13: StatusOpts = {"verbose":false};
// @ts-expect-error status.porcelain
export const witness14: StatusOpts = {"porcelain":1};
// @ts-expect-error status.nul
export const witness15: StatusOpts = {"nullTerminated":false};
import type { LogOpts } from '../../src/core/repo.js';
export const witness16: LogOpts = {};
// @ts-expect-error log.unsupported
export const witness17: LogOpts = {"stat":false};
import type { FetchOpts } from '../../src/core/repo.js';
export const witness18: FetchOpts = {};
// @ts-expect-error fetch.depth-unshallow
export const witness19: FetchOpts = {"depth":-1,"unshallow":true};
// @ts-expect-error fetch.deepen-depth
export const witness20: FetchOpts = {"deepen":-1,"depth":-1};
// @ts-expect-error fetch.deepen-unshallow
export const witness21: FetchOpts = {"deepen":-1,"unshallow":true};
// @ts-expect-error fetch.all-remote
export const witness22: FetchOpts = {"all":true,"remote":""};
// @ts-expect-error fetch.all-refspec
export const witness23: FetchOpts = {"all":true,"refspec":""};
// @ts-expect-error fetch.unsupported
export const witness24: FetchOpts = {"multiple":false};
import type { PushOpts } from '../../src/core/repo.js';
export const witness25: PushOpts = {};
// @ts-expect-error push.all-mirror-refspec
export const witness26: PushOpts = {"all":true,"refspec":""};
// @ts-expect-error push.all-tags
export const witness27: PushOpts = {"all":true,"tags":true};
// @ts-expect-error push.branches-mirror-refspec
export const witness28: PushOpts = {"branches":true,"refspec":""};
// @ts-expect-error push.branches-tags
export const witness29: PushOpts = {"branches":true,"tags":true};
// @ts-expect-error push.mirror-tags
export const witness30: PushOpts = {"mirror":true,"tags":true};
// @ts-expect-error push.delete-tags
export const witness31: PushOpts = {"deleteRefs":true,"refspec":"","tags":true};
// @ts-expect-error push.delete-refs
export const witness32: PushOpts = {"deleteRefs":true};
import type { AddOpts } from '../../src/core/repo.js';
export const witness33: AddOpts = {};
// @ts-expect-error add.all-update
export const witness34: AddOpts = {"all":true,"update":true};
// @ts-expect-error add.unsupported
export const witness35: AddOpts = {"patch":false};
import type { CheckoutBranchOpts } from '../../src/core/repo.js';
export const witness36: CheckoutBranchOpts = {};
// @ts-expect-error checkoutBranch.createBranch-forceCreateBranch-detach-orphan
export const witness37: CheckoutBranchOpts = {"forceCreateBranch":true,"orphan":true};
import type { CheckoutPathOpts } from '../../src/core/repo.js';
export const witness38: CheckoutPathOpts = {};
// @ts-expect-error checkoutPath.source-ours
export const witness39: CheckoutPathOpts = {"ours":true,"source":""};
// @ts-expect-error checkoutPath.source-theirs
export const witness40: CheckoutPathOpts = {"source":"","theirs":true};
import type { CommitOpts } from '../../src/core/repo.js';
export const witness41: CommitOpts = {};
// @ts-expect-error commit.message-file-reuseMessage
export const witness42: CommitOpts = {"message":"","reuseMessage":""};
// @ts-expect-error commit.fixup-squash
export const witness43: CommitOpts = {"fixup":"","squash":""};
// @ts-expect-error commit.include-only-all
export const witness44: CommitOpts = {"include":true,"only":true};
// @ts-expect-error commit.unsupported
export const witness45: CommitOpts = {"reeditMessage":""};
// @ts-expect-error commit.fixup-message-source
export const witness46: CommitOpts = {"fixup":"","reuseMessage":""};
// @ts-expect-error commit.author-reset
export const witness47: CommitOpts = {"author":"","resetAuthor":true};
// @ts-expect-error commit.all-pathspec-file
export const witness48: CommitOpts = {"all":true,"pathspecFromFile":""};
import type { DiffOpts } from '../../src/core/repo.js';
export const witness49: DiffOpts = {};
// @ts-expect-error diff.nameOnly-nameStatus
export const witness50: DiffOpts = {"nameOnly":true,"nameStatus":true};
// @ts-expect-error diff.unsupported
export const witness51: DiffOpts = {"noIndex":false};
// @ts-expect-error diff.nul
export const witness52: DiffOpts = {"nullTerminated":false};
import type { MergeOpts } from '../../src/core/repo.js';
export const witness53: MergeOpts = {};
// @ts-expect-error merge.abort-continue-quit
export const witness54: MergeOpts = {"continue":true,"quit":true};
// @ts-expect-error merge.abort-options
export const witness55: MergeOpts = {"abort":true,"verifySignatures":true};
// @ts-expect-error merge.continue-options
export const witness56: MergeOpts = {"continue":true,"verifySignatures":true};
// @ts-expect-error merge.quit-options
export const witness57: MergeOpts = {"quit":true,"verifySignatures":true};
// @ts-expect-error merge.squash-no-ff-no
export const witness58: MergeOpts = {"ff":"no","squash":true};
// @ts-expect-error merge.squash-no-ff-false
export const witness59: MergeOpts = {"ff":false,"squash":true};
import type { PullOpts } from '../../src/core/repo.js';
export const witness60: PullOpts = {};
// @ts-expect-error pull.depth-unshallow
export const witness61: PullOpts = {"depth":-1,"unshallow":true};
// @ts-expect-error pull.deepen-depth
export const witness62: PullOpts = {"deepen":-1,"depth":-1};
// @ts-expect-error pull.deepen-unshallow
export const witness63: PullOpts = {"deepen":-1,"unshallow":true};
import type { ResetOpts } from '../../src/core/repo.js';
export const witness64: ResetOpts = {};
// @ts-expect-error reset.intent-to-add-mode
export const witness65: ResetOpts = {"intentToAdd":true,"mode":"soft"};
import type { StashPushOpts } from '../../src/core/repo.js';
export const witness66: StashPushOpts = {};
// @ts-expect-error stashPush.staged
export const witness67: StashPushOpts = {"pathspecFromFile":"","staged":true};
// @ts-expect-error stashPush.pathspec
export const witness68: StashPushOpts = {"paths":[""],"pathspecFromFile":""};
import type { SwitchOpts } from '../../src/core/repo.js';
export const witness69: SwitchOpts = {};
// @ts-expect-error switch.create-forceCreate-detach-orphan
export const witness70: SwitchOpts = {"forceCreate":true,"orphan":true};
// @ts-expect-error switch.discard-merge
export const witness71: SwitchOpts = {"discard":true,"merge":true};
// @ts-expect-error switch.force-merge
export const witness72: SwitchOpts = {"force":true,"merge":true};
import type { TagCreateOpts } from '../../src/core/repo.js';
export const witness73: TagCreateOpts = {};
// @ts-expect-error tagCreate.message-file
export const witness74: TagCreateOpts = {"file":"","message":""};
import type { CherryPickOpts } from '../../src/core/repo.js';
export const witness75: CherryPickOpts = {};
// @ts-expect-error cherryPick.abort-continue-skip
export const witness76: CherryPickOpts = {"continue":true,"skip":true};
// @ts-expect-error cherryPick.unsupported
export const witness77: CherryPickOpts = {"noVerify":false};
// @ts-expect-error cherryPick.abort-options
export const witness78: CherryPickOpts = {"abort":true,"strategyOption":""};
// @ts-expect-error cherryPick.continue-options
export const witness79: CherryPickOpts = {"continue":true,"strategyOption":""};
// @ts-expect-error cherryPick.skip-options
export const witness80: CherryPickOpts = {"skip":true,"strategyOption":""};
// @ts-expect-error cherryPick.ff-signoff
export const witness81: CherryPickOpts = {"ff":true,"signoff":true};
// @ts-expect-error cherryPick.ff-noCommit
export const witness82: CherryPickOpts = {"ff":true,"noCommit":true};
// @ts-expect-error cherryPick.ff-appendCommitName
export const witness83: CherryPickOpts = {"appendCommitName":true,"ff":true};
// @ts-expect-error cherryPick.ff-edit
export const witness84: CherryPickOpts = {"edit":true,"ff":true};
import type { CleanOpts } from '../../src/core/repo.js';
export const witness85: CleanOpts = {};
// @ts-expect-error clean.ignored-onlyIgnored
export const witness86: CleanOpts = {"ignored":true,"onlyIgnored":true};
import type { RebaseOpts } from '../../src/core/repo.js';
export const witness87: RebaseOpts = {};
// @ts-expect-error rebase.abort-continue-skip
export const witness88: RebaseOpts = {"continue":true,"skip":true};
// @ts-expect-error rebase.keepBase-onto
export const witness89: RebaseOpts = {"keepBase":true,"onto":""};
// @ts-expect-error rebase.keepBase-root
export const witness90: RebaseOpts = {"keepBase":true,"root":true};
// @ts-expect-error rebase.apply-rebaseMerges
export const witness91: RebaseOpts = {"apply":true,"rebaseMerges":true};
// @ts-expect-error rebase.apply-strategy
export const witness92: RebaseOpts = {"apply":true,"strategy":""};
// @ts-expect-error rebase.apply-exec
export const witness93: RebaseOpts = {"apply":true,"exec":""};
// @ts-expect-error rebase.unsupported
export const witness94: RebaseOpts = {"interactive":false};
// @ts-expect-error rebase.root-forkPoint
export const witness95: RebaseOpts = {"forkPoint":true,"root":true};
import type { RestoreOpts } from '../../src/core/repo.js';
export const witness96: RestoreOpts = {};
// @ts-expect-error restore.staged-conflict
export const witness97: RestoreOpts = {"staged":true,"theirs":true};
// @ts-expect-error restore.source-ours
export const witness98: RestoreOpts = {"ours":true,"source":""};
// @ts-expect-error restore.source-theirs
export const witness99: RestoreOpts = {"source":"","theirs":true};
// @ts-expect-error restore.source-merge
export const witness100: RestoreOpts = {"merge":true,"source":""};
// @ts-expect-error restore.source-conflict
export const witness101: RestoreOpts = {"conflict":"merge","source":""};
import type { RevertOpts } from '../../src/core/repo.js';
export const witness102: RevertOpts = {};
// @ts-expect-error revert.abort-continue-skip
export const witness103: RevertOpts = {"continue":true,"skip":true};
// @ts-expect-error revert.unsupported
export const witness104: RevertOpts = {"noVerify":false};
// @ts-expect-error revert.abort-options
export const witness105: RevertOpts = {"abort":true,"strategyOption":""};
// @ts-expect-error revert.continue-options
export const witness106: RevertOpts = {"continue":true,"strategyOption":""};
// @ts-expect-error revert.skip-options
export const witness107: RevertOpts = {"skip":true,"strategyOption":""};
import type { SubmoduleOpts } from '../../src/core/repo.js';
export const witness108: SubmoduleOpts = {};
// @ts-expect-error submoduleUpdate.filter-init
export const witness109: SubmoduleOpts = {"filter":""};
import type { LfsPullOpts } from '../../src/core/repo.js';
export const witness110: LfsPullOpts = {};
// @ts-expect-error lfsPull.unsupported
export const witness111: LfsPullOpts = {"ref":""};
import type { LfsPushOpts } from '../../src/core/repo.js';
export const witness112: LfsPushOpts = {};
// @ts-expect-error lfsPush.ref-objectId
export const witness113: LfsPushOpts = {"objectId":"","ref":""};
import type { LfsStatusOpts } from '../../src/core/repo.js';
export const witness114: LfsStatusOpts = {};
// @ts-expect-error lfsStatus.unsupported
export const witness115: LfsStatusOpts = {"porcelain":false};
// @ts-expect-error lfsStatus.json
export const witness116: LfsStatusOpts = {"json":false};
import type { LfsFetchOpts } from '../../src/core/repo.js';
export const witness117: LfsFetchOpts = {};
// @ts-expect-error lfsFetch.all-include
export const witness118: LfsFetchOpts = {"all":true,"include":""};
// @ts-expect-error lfsFetch.all-exclude
export const witness119: LfsFetchOpts = {"all":true,"exclude":""};
// @ts-expect-error lfsFetch.all-recent
export const witness120: LfsFetchOpts = {"all":true,"recent":true};
import type { LfsLsFilesOpts } from '../../src/core/repo.js';
export const witness121: LfsLsFilesOpts = {};
// @ts-expect-error lfsLsFiles.unsupported
export const witness122: LfsLsFilesOpts = {"nameOnly":false};
// @ts-expect-error lfsLsFiles.json
export const witness123: LfsLsFilesOpts = {"json":false};
import type { LfsLocksOpts } from '../../src/core/repo.js';
export const witness124: LfsLocksOpts = {};
// @ts-expect-error lfsLocks.cached
export const witness125: LfsLocksOpts = {"cached":true,"path":"value"};
// @ts-expect-error lfsLocks.verify
export const witness126: LfsLocksOpts = {"path":"value","verify":true};
import type { LfsCheckoutOpts } from '../../src/core/repo.js';
export const witness127: LfsCheckoutOpts = {};
// @ts-expect-error lfsCheckout.stage
export const witness128: LfsCheckoutOpts = {"ours":true,"theirs":true,"to":"value"};
// @ts-expect-error lfsCheckout.destination-stage
export const witness129: LfsCheckoutOpts = {"to":"value"};
// @ts-expect-error lfsCheckout.base-destination
export const witness130: LfsCheckoutOpts = {"base":true};
// @ts-expect-error lfsCheckout.ours-destination
export const witness131: LfsCheckoutOpts = {"ours":true};
// @ts-expect-error lfsCheckout.theirs-destination
export const witness132: LfsCheckoutOpts = {"theirs":true};
// @ts-expect-error lfsCheckout.unknown-options
export const witness133: LfsCheckoutOpts = {"include":""};
import type { LfsMigrateInfoOpts } from '../../src/core/repo.js';
export const witness134: LfsMigrateInfoOpts = {};
// @ts-expect-error lfsMigrateInfo.everything-includeRef
export const witness135: LfsMigrateInfoOpts = {"everything":true,"includeRef":"value"};
// @ts-expect-error lfsMigrateInfo.everything-excludeRef
export const witness136: LfsMigrateInfoOpts = {"everything":true,"excludeRef":"value"};
// @ts-expect-error lfsMigrateInfo.everything-refs
export const witness137: LfsMigrateInfoOpts = {"everything":true,"refs":"value"};
// @ts-expect-error lfsMigrateInfo.fixup-patterns
export const witness138: LfsMigrateInfoOpts = {"fixup":true,"include":""};
// @ts-expect-error lfsMigrateInfo.fixup-pointers
export const witness139: LfsMigrateInfoOpts = {"fixup":true,"pointers":"follow"};
import type { LfsMigrateImportOpts } from '../../src/core/repo.js';
export const witness140: LfsMigrateImportOpts = {};
// @ts-expect-error lfsMigrateImport.everything-includeRef
export const witness141: LfsMigrateImportOpts = {"everything":true,"includeRef":"value"};
// @ts-expect-error lfsMigrateImport.everything-excludeRef
export const witness142: LfsMigrateImportOpts = {"everything":true,"excludeRef":"value"};
// @ts-expect-error lfsMigrateImport.everything-refs
export const witness143: LfsMigrateImportOpts = {"everything":true,"refs":"value"};
// @ts-expect-error lfsMigrateImport.unknown-options
export const witness144: LfsMigrateImportOpts = {"unit":""};
// @ts-expect-error lfsMigrateImport.no-rewrite-fixup
export const witness145: LfsMigrateImportOpts = {"files":[""],"fixup":true,"noRewrite":true};
// @ts-expect-error lfsMigrateImport.files
export const witness146: LfsMigrateImportOpts = {"noRewrite":true};
// @ts-expect-error lfsMigrateImport.file-mode
export const witness147: LfsMigrateImportOpts = {"files":[""]};
// @ts-expect-error lfsMigrateImport.refs-mode
export const witness148: LfsMigrateImportOpts = {"files":[""],"noRewrite":true,"refs":"value"};
// @ts-expect-error lfsMigrateImport.fixup-patterns
export const witness149: LfsMigrateImportOpts = {"fixup":true,"include":""};
import type { LfsMigrateExportOpts } from '../../src/core/repo.js';
export const witness150: LfsMigrateExportOpts = {"include":"value"};
// @ts-expect-error lfsMigrateExport.everything-includeRef
export const witness151: LfsMigrateExportOpts = {"everything":true,"include":"value","includeRef":"value"};
// @ts-expect-error lfsMigrateExport.everything-excludeRef
export const witness152: LfsMigrateExportOpts = {"everything":true,"excludeRef":"value","include":"value"};
// @ts-expect-error lfsMigrateExport.everything-refs
export const witness153: LfsMigrateExportOpts = {"everything":true,"include":"value","refs":"value"};
// @ts-expect-error lfsMigrateExport.include
export const witness154: LfsMigrateExportOpts = {};
// @ts-expect-error lfsMigrateExport.unknown-options
export const witness155: LfsMigrateExportOpts = {"include":"value","unit":""};
import type { WorktreeAddOpts } from '../../src/core/repo.js';
export const witness156: WorktreeAddOpts = {};
// @ts-expect-error worktreeAdd.branch-detach
export const witness157: WorktreeAddOpts = {"branch":"","detach":true};
// @ts-expect-error worktreeAdd.orphan-detach
export const witness158: WorktreeAddOpts = {"detach":true,"orphan":true};
// @ts-expect-error worktreeAdd.orphan-track
export const witness159: WorktreeAddOpts = {"orphan":true,"track":true};
// @ts-expect-error worktreeAdd.orphan-commitish
export const witness160: WorktreeAddOpts = {"commitish":"","orphan":true};
// @ts-expect-error worktreeAdd.orphan-no-checkout
export const witness161: WorktreeAddOpts = {"checkout":false,"orphan":true};
import type { RemoteAddOpts } from '../../src/core/repo.js';
export const witness162: RemoteAddOpts = {};
// @ts-expect-error remoteAdd.push-mirror-track
export const witness163: RemoteAddOpts = {"mirror":"push","track":""};
import type { RemoteSetHeadOpts } from '../../src/core/repo.js';
export const witness164: RemoteSetHeadOpts = {};
// @ts-expect-error remoteSetHead.auto-delete
export const witness165: RemoteSetHeadOpts = {"auto":true,"delete":true};
import type { ConfigGetOpts } from '../../src/core/repo.js';
export const witness166: ConfigGetOpts = {};
// @ts-expect-error configGet.all-default
export const witness167: ConfigGetOpts = {"all":true,"default":""};
import type { ConfigListOpts } from '../../src/core/repo.js';
export const witness168: ConfigListOpts = {};
// @ts-expect-error configList.unsupported
export const witness169: ConfigListOpts = {"nameOnly":false};
