// @typecheck-isolated: native parse-options completion outcomes.
// Generated by node scripts/parse-options-completion-corpus.mjs from independent Git outcomes.
import type { CheckedCommandArguments, GitCommandArgument, GitCommandName } from '../../src/commands/types.js';
type Check<T extends true> = T;
type Accepted<C extends GitCommandName, A extends readonly GitCommandArgument<C>[]> = [CheckedCommandArguments<C, A>] extends [never] ? false : true;
export type NativeCompletionCases = readonly [
  Check<Accepted<"stash list", [["--git-completion-helper"]]> extends true ? true : false>,
  Check<Accepted<"stash list", [{"operand":"--git-completion-helper"}]> extends true ? true : false>,
  Check<Accepted<"stash list", [{"operand":"--git-completion-helper"},["-h"]]> extends true ? true : false>,
  Check<Accepted<"stash list", [["-h"],{"operand":"--git-completion-helper"}]> extends true ? true : false>,
  Check<Accepted<"stash list", [{"operand":"--help-all"},{"operand":"--git-completion-helper"}]> extends true ? true : false>,
  Check<Accepted<"stash list", [["--git-completion-helper-all"]]> extends true ? true : false>,
  Check<Accepted<"stash list", [{"operand":"--git-completion-helper-all"}]> extends true ? true : false>,
  Check<Accepted<"stash list", [{"operand":"--git-completion-helper-all"},["-h"]]> extends true ? true : false>,
  Check<Accepted<"stash list", [["-h"],{"operand":"--git-completion-helper-all"}]> extends true ? true : false>,
  Check<Accepted<"stash list", [{"operand":"--help-all"},{"operand":"--git-completion-helper-all"}]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"migrate"},["--git-completion-helper"]]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"migrate"},{"operand":"--git-completion-helper"}]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"migrate"},["--git-completion-helper-all"]]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"migrate"},{"operand":"--git-completion-helper-all"}]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"verify"},["--git-completion-helper"]]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"verify"},{"operand":"--git-completion-helper"}]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"verify"},["--git-completion-helper-all"]]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"verify"},{"operand":"--git-completion-helper-all"}]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"exists"},["--git-completion-helper"]]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"exists"},{"operand":"--git-completion-helper"}]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"exists"},["--git-completion-helper-all"]]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"exists"},{"operand":"--git-completion-helper-all"}]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"list"},["--git-completion-helper"]]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"list"},{"operand":"--git-completion-helper"}]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"list"},["--git-completion-helper-all"]]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"list"},{"operand":"--git-completion-helper-all"}]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"optimize"},["--git-completion-helper"]]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"optimize"},{"operand":"--git-completion-helper"}]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"optimize"},["--git-completion-helper-all"]]> extends true ? true : false>,
  Check<Accepted<"refs", [{"operand":"optimize"},{"operand":"--git-completion-helper-all"}]> extends true ? true : false>,
];
